### ISSUE TITLE
Calling of undeclared function

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/Lab-work-0#1]
```
foo();

bar(){
    foo();
}

foo(){
    body;
}
```
works;

```
foo(){
    body;
}

bar(){
    foo();
}
```
works;

https://github.com/EdikGres/Lab-work-0/blob/254092d546beec440df3b2a53f95f51cda76ea91/Lab-work-0.c#L9
does not work

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.
YOU TOP BRO <3
